### ISSUE TITLE
Varying Amplitudes with get_eigenmode_coefficients()

### ISSUE THREAD

**Issue by smartalecH** [stevengj/meep#393]
It seems that the `get_eigenmode_coefficients()` function depends on the location of the monitor. I produced a simple example (similar to #380) where I varied the `y` location of a 2D waveguide (y=0, y=2 and y=4). As the waveguide moves further from the origin, the extracted forward coefficient's relative amplitude for the left monitor decreases (center plot). The right plot shows all three cases normalized.

![eigamps](https://user-images.githubusercontent.com/24902086/41988189-9ade3bda-79f8-11e8-97ee-74c09d3aeacb.png)

Since even the normalized plot is slightly off, it makes me wonder if something goes wrong before the overlap integral.

I have a feeling that the `get_eigenmode` C routine is producing slightly different field amplitudes for each of the three scenarios. Maybe I could produce another example that really exaggerates the differences. It also might be useful to generate a python wrapper for the C routine to debug this possiblity. This functionality would be useful for several other applications as well.

[debug_get_eig_amp.py.zip](https://github.com/stevengj/meep/files/2142184/debug_get_eig_amp.py.zip)

**Comment by ChristopherHogan** [comment]
`get_eigenmode` is already callable from python via `sim.fields.get_eigenmode`. However, there is no typemap to convert the returned `void*` to a Python version of `eigenmode_data`, so the results are currently useless.  What do you want to do with the result? I.e., which fields from the `eigenmode_data` struct would be useful for debugging? I ask because it's a lot of work to convert everything (especially the `maxwell_data`).

**Comment by HomerReid** [comment]
Probably all that's needed is for python users to be able to call `eigenmode_amplitude,` i.e. something like 

````

mode = get_eigenmode(...)

vec EvalPoint=[0.7, -0.2 , 0.3] # coordinates of evaluation point
ExAtEvalPoint = eigenmode_amplitude(mode, EvalPoint, meep.Ex)
HzAtEvalPoint = eigenmode_amplitude(mode, EvalPoint, meep.Hz)

```

Since `eigenmode_amplitude` expects its first input in the form of a `void *`, it should be possible to pass the return value of `get_eigenmode` directly without any need for python code to look inside the structure? I suspect this might already work, or could be make to work with very minor tweaks, not requiring wrapping the full complexity of the `eigenmode_data` struct.

**Comment by ChristopherHogan** [comment]
I verified that Homer's suggestion works. The only caveat is that the `vec` and `volume` arguments to `get_eigenmode` and `eigenmode_amplitude` must be SWIG-wrapped objects instead of the pure Python equivalents (`Vector3` and `Volume`). Here's an example (initialized as in `python/tests/mode_coeffs.py`. 
```python
# Initialize and run simulation
v = mp.volume(mp.vec(5, -3.5), mp.vec(5, 3.5))
mode = sim.fields.get_eigenmode(0.2, mp.X, v, v, 1, mp.vec(0, 0, 0), True, 0, 0, 1e-7, True)
eval_point = mp.vec(0.7, -0.2, 0.3)
ex_at_eval_point = mp.eigenmode_amplitude(mode, eval_point, mp.Ex)
hz_at_eval_point = mp.eigenmode_amplitude(mode, eval_point, mp.Hz)
```

**Comment by HomerReid** [comment]
Great, thanks! And thanks for the clear explanation of the distinctions between various types of objects---I hadn't appreciated these before, and they help to make sense of some inscrutable errors I've encountered in my rudimentary attempts at translating C++ code into python.

**Comment by smartalecH** [comment]
Thanks for the quick tutorial! I whipped up a little experiment:

First, I extracted the E field intensity from a simple MPB simulation. I used the same domain as the monitors described above.

Next, I used the code provided by @ChristopherHogan to extract the mode profiles at each of the three monitors described in the original question. Ideally, the `get_eigenmode` routine shouldn't care where each monitor is located, right? In other words, all four plots should match up.

Unfortunately, we see a discrepancy:

![eig_amp](https://user-images.githubusercontent.com/24902086/42060247-70620fbc-7ae3-11e8-9c3d-4c8fb9554ccf.png)

I took all three components of the E field and took the sum of the magnitude squared (i.e. |Ex|^2 + |Ey|^2 + |Ez|^2. I guess I could have calculated the Poynting vector as well since I also have the H field...

Either way, it seems to me like something is not right within the C routine.
[vis_debug_eig_amp.py.zip](https://github.com/stevengj/meep/files/2146951/vis_debug_eig_amp.py.zip)

**Comment by stevengj** [comment]
In suspect that the fix is to change [this line](https://github.com/stevengj/meep/blob/04424be888812df8d3107067c0a44ef72ac4c192/src/mpb.cpp#L489) to `edata->center         = eig_vol.center();`

**Comment by stevengj** [comment]
Actually, that would break the eigenmode source code.  I think the center should only be changed in the mode_coefficient code.

**Comment by stevengj** [comment]
I've pushed a quick fix.   Would be good to add a regression test for this to `make check`.

**Comment by smartalecH** [comment]
I think we are pretty close, but not 100% there. The above fix definitely resolves the monitor location error. In other words, monitors produce the same profiles regardless of their location within Meep's simulation domain:

![eig_fields](https://user-images.githubusercontent.com/24902086/42415167-2cc3f168-8203-11e8-9329-ee0ac684e386.png)

Unfortuntaely, the above profiles still don't align with what MPB predicts given the same geometry. While the relative field profiles of the `get_eigenmode` routine correlate perfectly with MPB, the absolute ampltitudes do not.

While debugging this issue, I noticed an interesting problem: as the monitor increases in size the ampltiudes tend to increase. The following figure illustrates this observation:

![mpb_meep_comparison](https://user-images.githubusercontent.com/24902086/42415228-b3254210-8204-11e8-9f2f-52a4ce56ea33.png)

The left column shows the permitivity profile seen by the monitor; I gradually increased the width of the monitor, but kept the waveguide constant. The middle column shows MPB's field profile for each of these three scenarios. As expected, the results don't depend on the monitor size (given there is enough cladding to actually produce a reasonable result, of course). The right column displays the `get_eigenmode` results. The fields increase with the monitor.

Relative amplitude errors could cause all sorts of problems for the eigenmode source, or when trying to extract S parameters.

I wish I could help more. Let me know if there is anything else I can do to resolve this issue.

[debug_fields.py.zip](https://github.com/stevengj/meep/files/2173150/debug_fields.py.zip)

**Comment by stevengj** [comment]
> While the relative field profiles of the get_eigenmode routine correlate perfectly with MPB, the absolute ampltitudes do not.

That's expected.   

First, realize that the "absolute amplitude" of an eigenmode is arbitrary — any multiple of the eigenmode is also an eigenmode.  (Just like for any eigenvector problem.)

MPB normalizes the modes so that ∫|𝐇|²=∫ε|𝐃|²=1, i.e. to unit "energy"—this is the appropriate normalization for dealing with different ω's at the same wavevector 𝐤.  Meep, on the other hand, normalizes the modes to unit *power* (∫ℜ[𝐄*×𝐇]⋅n̂=1).   This is the appropriate normalization for projecting into different modes (different propagation constants β) at the same ω.

**Comment by smartalecH** [comment]
> any multiple of the eigenmode is also an eigenmode. (Just like for any eigenvector problem.)

You're absolutely right, thank you! 

> I'm sure that we are doing the normalization during the mode decomposition correctly to get the "power amplitudes" as documented

If this is the case, then there shouldn't be any problems with different monitor sizes. Thank you for clarifying.

**Comment by stevengj** [comment]
Actually, it looks from the code that the `get_eigenmode` amplitude is off from that of MPB by a factor of `sqrt(volume)`.   (It doesn't affect the coefficient calculation because the normalization gets cancelled out.)

To change this, we could insert the following [before line 448 in mpb.c](https://github.com/stevengj/meep/blob/b4db14ca9771692fefe3f7b138409cf614debe76/src/mpb.cpp#L448):
```jl
phase /= sqrt(R[0][0]*R[1][1]*R[2][2]);
```
which should make it the same as the MPB normalization.

(Possibly some of the tests will need to be updated, since this will change the normalization of eigenmode sources.)

**Comment by smartalecH** [comment]
It looks like @HomerReid's pull request (#431) fixes the normalization differences between the meep implementation and MPB itself:

![mpb_meep_comparison](https://user-images.githubusercontent.com/24902086/43537525-cd782098-957c-11e8-83fd-665c85e3ab01.png)

Thank you for such a thorough bug fix!
